export const jverseJourney = {
  beginning: 'JVerse began with a clear vision: build a universe of solutions that solves real problems, not just programs. Smart Monitoring System became the flagship creation, designed to help businesses work with more efficiency and control. JVerse also represents an identity beyond programming—creator, strategist, and founder.',
  roles: 'Building JVerse meant working across several roles: developer, founder, marketer, trainer, and problem solver. The work included mastering Flutter, Node.js, and MySQL; shaping the JVerse brand; preparing onboarding materials and presentations; and navigating budget, technical, and operational challenges.',
  technical: 'The technical journey included framework-integration issues, scalability questions, long debugging sessions, and expanding the system from monitoring into POS and broader business management. Each resolved bug and deployment became a step toward a stronger, evolving product.',
  identity: 'The journey shaped an important realization: Jay-Be is not only a coder, but a developer who builds ecosystems and practical solutions. The focus is impact—creating systems that solve meaningful problems rather than chasing titles.',
  resilience: 'The journey has been demanding, with repeated revisions, context switching, and high expectations. That difficulty is part of the growth: every challenge has strengthened resilience, judgment, and the ability to carry complex work forward.',
  today: 'Today, Jay-Be is the Founder of JVerse, the system creator of Smart Monitoring System, a freelance full-stack developer, and an incoming software developer. JVerse is a legacy in progress: a universe of solutions built through resilience, adaptability, and vision.',
  developerAdvice: 'For aspiring developers and IT professionals: start with curiosity rather than prestige; master fundamentals before spreading too thin; build real projects; expect challenging debugging and revision; communicate and document clearly; and stay adaptable as tools change.',
  nonTechAdvice: 'For people outside tech: problem-solving is valuable in every field, technology is a tool rather than a requirement, collaboration creates better solutions, and every meaningful path has its own challenges. The goal is to find the universe you want to build.',
};
